### PR TITLE
Fix object proto pollution

### LINKED ISSUE #112: Bypass with Object.prototype pollution
```
Object.defineProperty(Object.prototype, 'haha', {
    enumerable: true,
    value: undefined
});

var f = document.createElement('iframe');
try {
    document.head.appendChild(f);
} catch (e) {}
f.contentWindow.alert(1);
```
Should use the `Object` from `natives` and `Object.create(null)`...

### PR DESCRIPTION
**Pull request by mmndaniel**
An attempt to fix #112

### CODE REVIEW

File: src/inserters.js [hunk 1]
```diff
@@ -41,18 +41,20 @@ function getHook(native, isRange, isSrcDoc) {
...
-        for (let i = 0; i < funcs.length; i++) {
-            const func = funcs[i];
-            const desc = Object.getOwnPropertyDescriptor(win[proto].prototype, func);
-            if (!desc) continue;
-            const prop = desc.set ? 'set' : 'value';
-            desc[prop] = getHook(desc[prop], proto === 'Range', func === 'srcdoc');
-            desc.configurable = true;
-            if (prop === 'value') {
-                desc.writable = true;
+        if (Object.hasOwnProperty.call(map, proto)) {
```
Comment (weizman) [inline src/inserters.js:44]: can we instead do:
```javascript
const protos = Object.getOwnPropertyNames(map);
for (let i = 0; i < protos.length; i++) {
  const proto = protos[i];
  const funcs = map[proto];
  ...
```
?

That way we save the extra indentation, and this should be safe because `Object` is a native and therefore `protos` too

Comment (weizman) [reply src/inserters.js:44]: (`protos` could also be declared in the upper scope, outside of the function, your call)

File: test/inserters.js [hunk 2]
```diff
@@ -184,4 +184,22 @@ describe('test DOM insertions', async function () {
         });
         expect(result).toBe('V');
     });
+
+    it('should fail to use atob of an iframe added after Object.prototype pollution', async function () {
```
Comment (weizman) [inline test/inserters.js:188]: excellent test, I think this would be more appropriate at `/test/overwrites.js`. Also can you add the `// reference: https://github.com/LavaMoat/snow/pull/112` comment please?

**Review by weizman — CHANGES_REQUESTED** [review]
Thank you @mmndaniel!

A few minor requests if you don't mind. Also, please add and commit `snow.js` and `snow.prod.js` files after running `yarn build` locally (you can see in former PRs we add the dst files with each change)

File: src/inserters.js (hunk 1 above)
Comment (mmndaniel) [reply src/inserters.js]: Good ideas! the 2nd will save the extra call. on it
